services:
  db:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: "postgres"
    restart: always
    shm_size: 120mb
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
